services:
  chainlit-dev:
    container_name: chainlit-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    env_file:
      - ../graph_agent.env
    volumes:
      - ../:/workspace
