services:
  chainlit-dev:
    container_name: chainlit-dev
    image: "mcr.microsoft.com/devcontainers/python:3.12-bookworm"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    tty: true
    env_file:
      - ../graph_agent.env
    volumes:
      - ../:/workspace:cached

  # VOICEVOX Engineは環境に合わせて以下のいずれかを起動する(可能ならGPUを使用することを推奨)
  # CPUのみを使用する場合
  voicevox_engine-dev:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true

  # Nvidia GPUを使用する場合
  # voicevox_engine-dev:
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   ports:
  #     - "50021:50021"
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
